lib/lunch_predictor_web/router.ex
defmodule LunchPredictorWeb.Router do
  use LunchPredictorWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LunchPredictorWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    resources "/lunches", LunchController
    resources "/providers", ProviderController
  end

  # Other scopes may use custom stacks.
  # scope "/api", LunchPredictorWeb do
  #   pipe_through :api
  # end
end

lib/lunch_predictor_web/templates/page/index.html.eex
<div class="row">
  <%= "Happy #{@day_of_week}!" %>
</div>
<div class="row">The most recent lunch provider was <b><%= @last_provider.name %></b></div>
<div class="row">My estimated lunch provider for today is <b><%= @estimate.name %></b></div>
<div class="row">
  <span><%= link "Lunches", to: lunch_path(@conn, :index) %></span>
  <span><%= link "Providers", to: provider_path(@conn, :index) %></span>
</div>
<div class="row">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>

        <th>Denormalized Posterior</th>
      </tr>
    </thead>
    <tbody>
      <%= for {provider, posterior} <- @providers_with_posteriors do %>
        <tr>
          <td><%= provider.name %></td>

          <td><%= posterior %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>